### ISSUE TITLE
teensy 4.0 compatibility

### ISSUE THREAD

**Issue by cjf-fuller** [midilab/aciduino#54]
Hi, great project thanks for sharing - sorry if this is a dumb question, I am very much a beginner. 

Should I expect the `Final v2.0.0` release to be compatible with a teensy 4.0 board? I can see in `protoboard.h` a comment saying the file is for teensy 3.2+ on protoboard, would this include 4.0? Many thanks!

**Comment by cjf-fuller** [comment]
Hi @midilab , thanks for the hints, I am making (slow) progress - I believe there is a compatibility issue with the [initTimer() function](https://github.com/midilab/uCtrl/blob/f826e097d271bde7a4e1ed5f9a546adcbb0a165c/platforms/teensy.h#L14) and 4.0. 

If i disable this function I get the `system_page` loading completely on screen (but unresponsive as expected). However with the function enabled I only get the first 40 pixels displaying before the process crashes and reboots. Will keep looking, suspect it could be due to difference in cpu/processing speedbetween 3.2 and 4.0 - thought i'd update you incase you had any more hints on where to look? Thanks!

**Comment by midilab** [comment]
@cjf-fuller You can try to use the develop branch, lots os changes were made to avoid such of a crashes along different platforms at uCtrl the library wich aciduino is based on.

Just a remind, you need to initialize sub repositories.

```shell
you@acidlab:~$ git clone https://github.com/midilab/aciduino.git
you@acidlab:~$ cd aciduino/
you@acidlab:~$ git checkout develop
you@acidlab:~$ git submodule update --init --recursive
```

Let me know about the develop branch experiments!

**Comment by cjf-fuller** [comment]
Should have mentioned, I am already working from the develop branch of aciduino - I will keep experimenting though

Only other update I have made was changing `defined(USB_MIDI_SERIAL)` to `defined(USB_MIDI)` in `midi.hpp` and `midi_interface.hpp`, as when I was flashing the teensy with MIDI & SERIAL USB Type I got 

```
Compilation error: 'class usb_midi_class' has no member named 'setHandlePitchBend'; did you mean 'sendPitchBend'?"
```

and switching to USB Type MIDI and updating USB_MIDI_SERIAL -> USB_MIDI seemed to help.

**Comment by midilab** [comment]
@cjf-fuller this compilation error looks like recently changes on teensy library for MIDI(they were the only ones until this date to use different name for hanlders callback setup for MIDI), i will try to investigate it as soon as possible. 

But in case they really change the library, you can just rename setHandlePitchBend() to sendPitchBend() instead of change the defined statements.

Other option is to stick with a know working version of teensy core library instead of latest one
Teensyduino 1.56 is the one supose to work fine.

**Comment by cjf-fuller** [comment]
Can confirm it is working with Teensyduino 1.56 - thank you very much for the help. I tried the function rename, but seems like there some typing changes required as well. I will try and investigate what changes are needed to support the latest teensy core library

**Comment by midilab** [comment]
@cjf-fuller great to know! 

and my bad, this kinda of info (core lib version requeirments) shuold be inside the README.md as reference for install and compile. i will update it asap!

**Comment by midilab** [comment]
did you have to change anything in protoboard.h ffor teensy to make it work? like pins or any other change?

**Comment by cjf-fuller** [comment]
> did you have to change anything in protoboard.h ffor teensy to make it work? like pins or any other change?

Sorry for the late reply, but no pin changes required! The exact same protoboard.h works with Teensyduino 1.56 - thanks!
